# Generated by Django 4.2.7 on 2025-04-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_allowedemaildomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/profile.jpg', upload_to='profile_pics'),
        ),
    ]
